/**
 * REDFLIX — Data Layer
 * -----------------------------------------------------------------------
 * All catalog content lives here, decoupled from rendering. This lets
 * every page (home, detail) reuse the same source of truth without
 * touching DOM logic.
 *
 * Every title carries:
 *  - `spine`   REDFLIX's own catalog index, in the spirit of a numbered
 *                film collection. Shown in the UI, never changes.
 *  - `id`       Short numeric slug used in URLs (pelicula.html?id=001).
 *                Internal only — never shown to the person.
 *  - `tone`     Selects a poster gradient family (see components.css,
 *                .poster--tone-*). Stands in for real artwork.
 *
 * `description` is the short blurb used on hover cards and previews.
 * `synopsis` is the longer version shown on the detail page.
 */

const REDFLIX_CATALOG = {
  featured: {
    id: "001",
    spine: "RX–001",
    title: "Vestigio",
    year: 2024,
    duration: "2h 11m",
    rating: "4.8",
    maturity: "16+",
    genres: ["Drama", "Misterio"],
    director: "Lucía Ferreiro",
    cast: ["Julieta Vengoechea", "Ramiro Aldunate", "Constanza Riquelme"],
    languages: ["Español", "Inglés", "Francés"],
    tagline: "Todo lo que se entierra, vuelve a la superficie.",
    description: "Una arquitecta regresa al pueblo costero donde creció para reclamar la casa de su padre, y descubre que los cimientos guardan algo que la familia pasó tres décadas ocultando.",
    synopsis: "Una arquitecta regresa al pueblo costero donde creció para reclamar la casa de su padre, y descubre que los cimientos guardan algo que la familia pasó tres décadas ocultando. Un relato pausado que confía en el espectador para llenar los vacíos.",
    tone: "crimson",
  },

  categories: [
    {
      id: "trending",
      label: "Tendencias esta semana",
      titles: [
        {
          id: "002",
          spine: "RX–014",
          title: "Umbral",
          year: 2023,
          duration: "1h 58m",
          rating: "4.6",
          maturity: "13+",
          genres: ["Sci-Fi", "Thriller"],
          director: "Renata Bosch",
          cast: ["Federico Salgueiro", "Amparo Deleón", "Santiago Otazú"],
          languages: ["Español", "Inglés"],
          description: "Un ingeniero de sistemas descubre que la estación espacial donde trabaja lleva trece años repitiendo el mismo turno.",
          synopsis: "Un ingeniero de sistemas descubre que la estación espacial donde trabaja lleva trece años repitiendo el mismo turno. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "slate",
        },
        {
          id: "003",
          spine: "RX–022",
          title: "Última Función",
          year: 2022,
          duration: "2h 04m",
          rating: "4.7",
          maturity: "13+",
          genres: ["Drama"],
          director: "Camila Oyarzún",
          cast: ["Delfina Marchetti", "Bautista Ercolano", "Milagros Sanhueza"],
          languages: ["Español", "Inglés", "Subtítulos en Portugués"],
          description: "El proyeccionista de un cine a punto de cerrar decide dar una última función solo para sí mismo.",
          synopsis: "El proyeccionista de un cine a punto de cerrar decide dar una última función solo para sí mismo. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "amber",
        },
        {
          id: "004",
          spine: "RX–031",
          title: "Contraluz",
          year: 2024,
          duration: "1h 47m",
          rating: "4.3",
          maturity: "13+",
          genres: ["Romance", "Drama"],
          director: "Valentina Orpi",
          cast: ["Agustín Perales", "Rocío Bermello", "Ezequiel Tabárez"],
          languages: ["Español", "Portugués"],
          description: "Dos fotógrafos de guerra se reencuentran una década después en la misma habitación de hotel.",
          synopsis: "Dos fotógrafos de guerra se reencuentran una década después en la misma habitación de hotel. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "crimson",
        },
        {
          id: "005",
          spine: "RX–007",
          title: "El Silencio de Marzo",
          year: 2021,
          duration: "2h 19m",
          rating: "4.9",
          maturity: "13+",
          genres: ["Drama", "Histórico"],
          director: "Lucía Ferreiro",
          cast: ["Antonia Wroblewski", "Facundo Iriarte", "Guadalupe Núñez del Prado"],
          languages: ["Español"],
          description: "En un pueblo minero, una huelga silenciosa se convierte en la resistencia más larga del siglo.",
          synopsis: "En un pueblo minero, una huelga silenciosa se convierte en la resistencia más larga del siglo. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "moss",
        },
        {
          id: "006",
          spine: "RX–045",
          title: "Punto Ciego",
          year: 2023,
          duration: "1h 52m",
          rating: "4.2",
          maturity: "13+",
          genres: ["Thriller"],
          director: "Renata Bosch",
          cast: ["Ignacio Zeballos", "Josefina Arze", "Matías Cordovez"],
          languages: ["Español", "Inglés", "Francés"],
          description: "Una detective con pérdida parcial de visión investiga un crimen que solo ella parece no poder ver del todo.",
          synopsis: "Una detective con pérdida parcial de visión investiga un crimen que solo ella parece no poder ver del todo. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "slate",
        },
        {
          id: "007",
          spine: "RX–019",
          title: "Marea Alta",
          year: 2020,
          duration: "1h 41m",
          rating: "4.4",
          maturity: "13+",
          genres: ["Drama", "Familia"],
          director: "Camila Oyarzún",
          cast: ["Carolina Pastrana", "Leandro Fiorentino", "Julieta Vengoechea"],
          languages: ["Español", "Inglés"],
          description: "Tres hermanas se reúnen en la casa de verano de su infancia para decidir si venderla.",
          synopsis: "Tres hermanas se reúnen en la casa de verano de su infancia para decidir si venderla. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "teal",
        },
        {
          id: "008",
          spine: "RX–052",
          title: "Código Ausente",
          year: 2024,
          duration: "2h 08m",
          rating: "4.5",
          maturity: "13+",
          genres: ["Sci-Fi"],
          director: "Valentina Orpi",
          cast: ["Ramiro Aldunate", "Constanza Riquelme", "Federico Salgueiro"],
          languages: ["Español", "Inglés", "Subtítulos en Portugués"],
          description: "Una programadora encuentra líneas de código que nadie en su equipo recuerda haber escrito.",
          synopsis: "Una programadora encuentra líneas de código que nadie en su equipo recuerda haber escrito. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "amber",
        },
        {
          id: "009",
          spine: "RX–011",
          title: "Los Herederos",
          year: 2019,
          duration: "2h 26m",
          rating: "4.1",
          maturity: "13+",
          genres: ["Drama"],
          director: "Lucía Ferreiro",
          cast: ["Amparo Deleón", "Santiago Otazú", "Delfina Marchetti"],
          languages: ["Español", "Portugués"],
          description: "La muerte de un patriarca destapa una guerra silenciosa por el negocio familiar de vinos.",
          synopsis: "La muerte de un patriarca destapa una guerra silenciosa por el negocio familiar de vinos. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "crimson",
        }
      ],
    },
    {
      id: "accion",
      label: "Acción",
      titles: [
        {
          id: "010",
          spine: "RX–063",
          title: "Perímetro",
          year: 2023,
          duration: "1h 55m",
          rating: "4.3",
          maturity: "13+",
          genres: ["Acción"],
          director: "Renata Bosch",
          cast: ["Bautista Ercolano", "Milagros Sanhueza", "Agustín Perales"],
          languages: ["Español"],
          description: "Un equipo de escolta privada tiene noventa minutos para sacar a un testigo de una ciudad sitiada.",
          synopsis: "Un equipo de escolta privada tiene noventa minutos para sacar a un testigo de una ciudad sitiada. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "slate",
        },
        {
          id: "011",
          spine: "RX–028",
          title: "Ronda Nocturna",
          year: 2022,
          duration: "1h 49m",
          rating: "4.0",
          maturity: "13+",
          genres: ["Acción", "Crimen"],
          director: "Camila Oyarzún",
          cast: ["Rocío Bermello", "Ezequiel Tabárez", "Antonia Wroblewski"],
          languages: ["Español", "Inglés", "Francés"],
          description: "Una oficial de tránsito descubre una red de contrabando que opera durante su propio turno.",
          synopsis: "Una oficial de tránsito descubre una red de contrabando que opera durante su propio turno. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "crimson",
        },
        {
          id: "012",
          spine: "RX–071",
          title: "Frontera Sur",
          year: 2024,
          duration: "2h 02m",
          rating: "4.4",
          maturity: "13+",
          genres: ["Acción", "Drama"],
          director: "Valentina Orpi",
          cast: ["Facundo Iriarte", "Guadalupe Núñez del Prado", "Ignacio Zeballos"],
          languages: ["Español", "Inglés"],
          description: "Un ex militar cruza tres países para encontrar a la hija que no sabía que tenía.",
          synopsis: "Un ex militar cruza tres países para encontrar a la hija que no sabía que tenía. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "amber",
        },
        {
          id: "013",
          spine: "RX–039",
          title: "Contraataque",
          year: 2021,
          duration: "1h 44m",
          rating: "3.9",
          maturity: "13+",
          genres: ["Acción"],
          director: "Lucía Ferreiro",
          cast: ["Josefina Arze", "Matías Cordovez", "Carolina Pastrana"],
          languages: ["Español", "Inglés", "Subtítulos en Portugués"],
          description: "Un grupo de rehenes coordina un plan de escape usando solo lo que hay en la sala de juntas.",
          synopsis: "Un grupo de rehenes coordina un plan de escape usando solo lo que hay en la sala de juntas. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "slate",
        },
        {
          id: "014",
          spine: "RX–056",
          title: "Zona Cero",
          year: 2020,
          duration: "2h 15m",
          rating: "4.2",
          maturity: "13+",
          genres: ["Acción", "Sci-Fi"],
          director: "Renata Bosch",
          cast: ["Leandro Fiorentino", "Julieta Vengoechea", "Ramiro Aldunate"],
          languages: ["Español", "Portugués"],
          description: "Un equipo de rescate entra a una ciudad en cuarentena para recuperar algo más que sobrevivientes.",
          synopsis: "Un equipo de rescate entra a una ciudad en cuarentena para recuperar algo más que sobrevivientes. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "moss",
        },
        {
          id: "015",
          spine: "RX–084",
          title: "Punto de Fuga",
          year: 2023,
          duration: "1h 51m",
          rating: "4.1",
          maturity: "13+",
          genres: ["Acción", "Thriller"],
          director: "Camila Oyarzún",
          cast: ["Constanza Riquelme", "Federico Salgueiro", "Amparo Deleón"],
          languages: ["Español"],
          description: "Una piloto de pruebas roba su propio prototipo antes de que lo militaricen.",
          synopsis: "Una piloto de pruebas roba su propio prototipo antes de que lo militaricen. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "teal",
        },
        {
          id: "016",
          spine: "RX–018",
          title: "Al Filo",
          year: 2019,
          duration: "1h 58m",
          rating: "3.8",
          maturity: "13+",
          genres: ["Acción"],
          director: "Valentina Orpi",
          cast: ["Santiago Otazú", "Delfina Marchetti", "Bautista Ercolano"],
          languages: ["Español", "Inglés", "Francés"],
          description: "Dos rivales de escalada quedan atrapados juntos en la misma pared, sin cuerda de sobra para ambos.",
          synopsis: "Dos rivales de escalada quedan atrapados juntos en la misma pared, sin cuerda de sobra para ambos. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "crimson",
        }
      ],
    },
    {
      id: "drama",
      label: "Drama",
      titles: [
        {
          id: "017",
          spine: "RX–009",
          title: "Sala de Espera",
          year: 2022,
          duration: "1h 39m",
          rating: "4.6",
          maturity: "13+",
          genres: ["Drama"],
          director: "Lucía Ferreiro",
          cast: ["Milagros Sanhueza", "Agustín Perales", "Rocío Bermello"],
          languages: ["Español", "Inglés"],
          description: "Ocho desconocidos comparten una sala de hospital durante la noche más larga de sus vidas.",
          synopsis: "Ocho desconocidos comparten una sala de hospital durante la noche más larga de sus vidas. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "moss",
        },
        {
          id: "018",
          spine: "RX–033",
          title: "El Peso del Agua",
          year: 2021,
          duration: "2h 12m",
          rating: "4.7",
          maturity: "13+",
          genres: ["Drama", "Familia"],
          director: "Renata Bosch",
          cast: ["Ezequiel Tabárez", "Antonia Wroblewski", "Facundo Iriarte"],
          languages: ["Español", "Inglés", "Subtítulos en Portugués"],
          description: "Un pescador enseña a su hija el oficio mientras el mar del que dependen empieza a desaparecer.",
          synopsis: "Un pescador enseña a su hija el oficio mientras el mar del que dependen empieza a desaparecer. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "teal",
        },
        {
          id: "019",
          spine: "RX–047",
          title: "Cartas que no Llegaron",
          year: 2020,
          duration: "1h 56m",
          rating: "4.5",
          maturity: "13+",
          genres: ["Drama", "Romance"],
          director: "Camila Oyarzún",
          cast: ["Guadalupe Núñez del Prado", "Ignacio Zeballos", "Josefina Arze"],
          languages: ["Español", "Portugués"],
          description: "Un cartero jubilado decide entregar, cuarenta años tarde, la correspondencia que nunca repartió.",
          synopsis: "Un cartero jubilado decide entregar, cuarenta años tarde, la correspondencia que nunca repartió. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "amber",
        },
        {
          id: "020",
          spine: "RX–061",
          title: "Otoño Interior",
          year: 2023,
          duration: "2h 05m",
          rating: "4.4",
          maturity: "13+",
          genres: ["Drama"],
          director: "Valentina Orpi",
          cast: ["Matías Cordovez", "Carolina Pastrana", "Leandro Fiorentino"],
          languages: ["Español"],
          description: "Una directora de orquesta pierde el oído gradualmente mientras prepara su última temporada.",
          synopsis: "Una directora de orquesta pierde el oído gradualmente mientras prepara su última temporada. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "slate",
        },
        {
          id: "021",
          spine: "RX–025",
          title: "Las Horas Quietas",
          year: 2018,
          duration: "1h 48m",
          rating: "4.3",
          maturity: "13+",
          genres: ["Drama"],
          director: "Lucía Ferreiro",
          cast: ["Julieta Vengoechea", "Ramiro Aldunate", "Constanza Riquelme"],
          languages: ["Español", "Inglés", "Francés"],
          description: "Una enfermera de cuidados paliativos documenta las últimas conversaciones de sus pacientes.",
          synopsis: "Una enfermera de cuidados paliativos documenta las últimas conversaciones de sus pacientes. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "crimson",
        },
        {
          id: "022",
          spine: "RX–073",
          title: "Suelo Firme",
          year: 2024,
          duration: "2h 01m",
          rating: "4.2",
          maturity: "13+",
          genres: ["Drama", "Histórico"],
          director: "Renata Bosch",
          cast: ["Federico Salgueiro", "Amparo Deleón", "Santiago Otazú"],
          languages: ["Español", "Inglés"],
          description: "Una familia de aparceros disputa la tierra que trabajó durante tres generaciones sin ser dueña.",
          synopsis: "Una familia de aparceros disputa la tierra que trabajó durante tres generaciones sin ser dueña. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "moss",
        }
      ],
    },
    {
      id: "scifi",
      label: "Ciencia Ficción",
      titles: [
        {
          id: "023",
          spine: "RX–088",
          title: "Segunda Órbita",
          year: 2024,
          duration: "2h 09m",
          rating: "4.6",
          maturity: "13+",
          genres: ["Sci-Fi"],
          director: "Camila Oyarzún",
          cast: ["Delfina Marchetti", "Bautista Ercolano", "Milagros Sanhueza"],
          languages: ["Español", "Inglés", "Subtítulos en Portugués"],
          description: "La tripulación de una misión de retorno descubre que la Tierra a la que vuelven no es la que dejaron.",
          synopsis: "La tripulación de una misión de retorno descubre que la Tierra a la que vuelven no es la que dejaron. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "slate",
        },
        {
          id: "024",
          spine: "RX–016",
          title: "Materia Oscura",
          year: 2022,
          duration: "1h 57m",
          rating: "4.3",
          maturity: "13+",
          genres: ["Sci-Fi", "Thriller"],
          director: "Valentina Orpi",
          cast: ["Agustín Perales", "Rocío Bermello", "Ezequiel Tabárez"],
          languages: ["Español", "Portugués"],
          description: "Un físico encuentra evidencia de que su laboratorio existe en dos lugares al mismo tiempo.",
          synopsis: "Un físico encuentra evidencia de que su laboratorio existe en dos lugares al mismo tiempo. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "teal",
        },
        {
          id: "025",
          spine: "RX–042",
          title: "El Último Jardín",
          year: 2021,
          duration: "2h 14m",
          rating: "4.5",
          maturity: "13+",
          genres: ["Sci-Fi", "Drama"],
          director: "Lucía Ferreiro",
          cast: ["Antonia Wroblewski", "Facundo Iriarte", "Guadalupe Núñez del Prado"],
          languages: ["Español"],
          description: "En una Tierra sin polinizadores, una botánica cría la última generación de abejas en secreto.",
          synopsis: "En una Tierra sin polinizadores, una botánica cría la última generación de abejas en secreto. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "moss",
        },
        {
          id: "026",
          spine: "RX–067",
          title: "Réplica",
          year: 2023,
          duration: "1h 46m",
          rating: "4.0",
          maturity: "13+",
          genres: ["Sci-Fi"],
          director: "Renata Bosch",
          cast: ["Ignacio Zeballos", "Josefina Arze", "Matías Cordovez"],
          languages: ["Español", "Inglés", "Francés"],
          description: "Una copia digital de una mujer fallecida empieza a tomar decisiones que la original nunca habría tomado.",
          synopsis: "Una copia digital de una mujer fallecida empieza a tomar decisiones que la original nunca habría tomado. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "crimson",
        },
        {
          id: "027",
          spine: "RX–050",
          title: "Horizonte Cero",
          year: 2020,
          duration: "2h 03m",
          rating: "4.1",
          maturity: "13+",
          genres: ["Sci-Fi", "Acción"],
          director: "Camila Oyarzún",
          cast: ["Carolina Pastrana", "Leandro Fiorentino", "Julieta Vengoechea"],
          languages: ["Español", "Inglés"],
          description: "Los últimos ingenieros de un satélite a la deriva tienen una órbita para decidir su destino.",
          synopsis: "Los últimos ingenieros de un satélite a la deriva tienen una órbita para decidir su destino. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "amber",
        }
      ],
    },
    {
      id: "thriller",
      label: "Thriller",
      titles: [
        {
          id: "028",
          spine: "RX–005",
          title: "Doble Turno",
          year: 2023,
          duration: "1h 43m",
          rating: "4.4",
          maturity: "13+",
          genres: ["Thriller"],
          director: "Valentina Orpi",
          cast: ["Ramiro Aldunate", "Constanza Riquelme", "Federico Salgueiro"],
          languages: ["Español", "Inglés", "Subtítulos en Portugués"],
          description: "Una operadora de emergencias empieza a recibir llamadas de un crimen que aún no ha ocurrido.",
          synopsis: "Una operadora de emergencias empieza a recibir llamadas de un crimen que aún no ha ocurrido. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "crimson",
        },
        {
          id: "029",
          spine: "RX–037",
          title: "El Inquilino",
          year: 2022,
          duration: "1h 51m",
          rating: "4.2",
          maturity: "13+",
          genres: ["Thriller", "Misterio"],
          director: "Lucía Ferreiro",
          cast: ["Amparo Deleón", "Santiago Otazú", "Delfina Marchetti"],
          languages: ["Español", "Portugués"],
          description: "Una mujer descubre que el hombre que subarrienda su departamento no es quien dijo ser.",
          synopsis: "Una mujer descubre que el hombre que subarrienda su departamento no es quien dijo ser. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "slate",
        },
        {
          id: "030",
          spine: "RX–059",
          title: "Cadena de Frío",
          year: 2021,
          duration: "1h 58m",
          rating: "4.3",
          maturity: "13+",
          genres: ["Thriller", "Crimen"],
          director: "Renata Bosch",
          cast: ["Bautista Ercolano", "Milagros Sanhueza", "Agustín Perales"],
          languages: ["Español"],
          description: "Un inspector de sanidad destapa una red criminal escondida en la cadena de distribución de alimentos.",
          synopsis: "Un inspector de sanidad destapa una red criminal escondida en la cadena de distribución de alimentos. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "teal",
        },
        {
          id: "031",
          spine: "RX–081",
          title: "Sin Testigos",
          year: 2024,
          duration: "1h 49m",
          rating: "4.0",
          maturity: "13+",
          genres: ["Thriller"],
          director: "Camila Oyarzún",
          cast: ["Rocío Bermello", "Ezequiel Tabárez", "Antonia Wroblewski"],
          languages: ["Español", "Inglés", "Francés"],
          description: "La única testigo de un asalto empieza a dudar de su propia memoria del incidente.",
          synopsis: "La única testigo de un asalto empieza a dudar de su propia memoria del incidente. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "moss",
        },
        {
          id: "032",
          spine: "RX–024",
          title: "Vecino de Piso",
          year: 2019,
          duration: "1h 55m",
          rating: "3.9",
          maturity: "13+",
          genres: ["Thriller"],
          director: "Valentina Orpi",
          cast: ["Facundo Iriarte", "Guadalupe Núñez del Prado", "Ignacio Zeballos"],
          languages: ["Español", "Inglés"],
          description: "Un hombre que trabaja desde casa se convierte en el único testigo de lo que pasa en el edificio de enfrente.",
          synopsis: "Un hombre que trabaja desde casa se convierte en el único testigo de lo que pasa en el edificio de enfrente. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "amber",
        }
      ],
    },
    {
      id: "documentales",
      label: "Documentales",
      titles: [
        {
          id: "033",
          spine: "RX–003",
          title: "La Fábrica de Sal",
          year: 2022,
          duration: "1h 22m",
          rating: "4.7",
          maturity: "13+",
          genres: ["Documental"],
          director: "Lucía Ferreiro",
          cast: ["Josefina Arze", "Matías Cordovez", "Carolina Pastrana"],
          languages: ["Español", "Inglés", "Subtítulos en Portugués"],
          description: "Un retrato íntimo de la última familia que extrae sal de forma artesanal en la costa.",
          synopsis: "Un retrato íntimo de la última familia que extrae sal de forma artesanal en la costa. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "teal",
        },
        {
          id: "034",
          spine: "RX–029",
          title: "Voces del Archivo",
          year: 2021,
          duration: "1h 34m",
          rating: "4.5",
          maturity: "13+",
          genres: ["Documental", "Histórico"],
          director: "Renata Bosch",
          cast: ["Leandro Fiorentino", "Julieta Vengoechea", "Ramiro Aldunate"],
          languages: ["Español", "Portugués"],
          description: "Grabaciones olvidadas de una radio comunitaria reconstruyen la historia oral de un barrio desaparecido.",
          synopsis: "Grabaciones olvidadas de una radio comunitaria reconstruyen la historia oral de un barrio desaparecido. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "amber",
        },
        {
          id: "035",
          spine: "RX–054",
          title: "El Otro Lado del Mapa",
          year: 2023,
          duration: "1h 28m",
          rating: "4.4",
          maturity: "13+",
          genres: ["Documental"],
          director: "Camila Oyarzún",
          cast: ["Constanza Riquelme", "Federico Salgueiro", "Amparo Deleón"],
          languages: ["Español"],
          description: "Cartógrafos independientes documentan territorios que los mapas oficiales aún no reconocen.",
          synopsis: "Cartógrafos independientes documentan territorios que los mapas oficiales aún no reconocen. Un relato pausado que confía en el espectador para llenar los vacíos.",
          tone: "moss",
        },
        {
          id: "036",
          spine: "RX–076",
          title: "Manos de Taller",
          year: 2020,
          duration: "1h 19m",
          rating: "4.6",
          maturity: "13+",
          genres: ["Documental"],
          director: "Valentina Orpi",
          cast: ["Santiago Otazú", "Delfina Marchetti", "Bautista Ercolano"],
          languages: ["Español", "Inglés", "Francés"],
          description: "Tres generaciones de un mismo taller de lutería hablan del oficio que se niega a desaparecer.",
          synopsis: "Tres generaciones de un mismo taller de lutería hablan del oficio que se niega a desaparecer. Una historia sobre lo que decidimos callar, y lo que finalmente nos obliga a hablar.",
          tone: "slate",
        }
      ],
    }
  ],
};

/**
 * Flat lookup used by the detail page (pelicula.html) to find a title by
 * id without the caller needing to know which category it lives in.
 */
const REDFLIX_ALL_TITLES = [
  REDFLIX_CATALOG.featured,
  ...REDFLIX_CATALOG.categories.flatMap((c) =>
    c.titles.map((t) => ({ ...t, categoryId: c.id, categoryLabel: c.label }))
  ),
];

function findTitleById(id) {
  return REDFLIX_ALL_TITLES.find((t) => t.id === id) || null;
}

function findSimilarTitles(target, limit = 8) {
  return REDFLIX_ALL_TITLES.filter(
    (t) =>
      t.id !== target.id && t.genres.some((g) => target.genres.includes(g))
  ).slice(0, limit);
}

function findMoreLikeThis(target, exclude = [], limit = 8) {
  const excludeIds = new Set([target.id, ...exclude.map((t) => t.id)]);
  const sameCategory = REDFLIX_ALL_TITLES.filter(
    (t) => !excludeIds.has(t.id) && t.categoryId === target.categoryId
  );
  if (sameCategory.length >= limit) return sameCategory.slice(0, limit);

  const fallback = REDFLIX_ALL_TITLES.filter(
    (t) => !excludeIds.has(t.id) && !sameCategory.includes(t)
  );
  return [...sameCategory, ...fallback].slice(0, limit);
}
